# Generated by Django 4.1.2 on 2023-06-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(blank=True, default='Dog_name', null=True)),
                ('breed', models.TextField(blank=True, default='Dog_Breed', null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
