# Generated by Django 4.1.2 on 2023-06-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_uploadedimage_user_id_uploadedimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
